name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      allow-publish:
        description: Allow Publishing
        required: true
        default: 'false'
      version:
        description: Version to Publish
        required: false
        default: '0.0.X-pg'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: |
          Castaway.Base/bin/Release/Castaway.Base.${{ github.event.inputs.version }}.nupkg
  publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.allow-publish == 'true'
    needs: build
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Download
        uses: actions/download-artifact@v2
        with: 
          name: nupkgs
      - name: Publish
        run: |
          ls -R
        # dotnet nuget add source --username LiamCoal --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/LiamCoalStudio/index.json
        # dotnet nuget push Castaway.Base/bin/Release/Castaway.Base.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
