name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      allow-publish:
        description: Allow Publishing
        required: true
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Add Source
      if: github.event.inputs.allow-publish == 'true'
      run: dotnet nuget add source --username LiamCoal --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/LiamCoalStudio/index.json
    - name: Publish
      if: github.event.inputs.allow-publish == 'true'
      run: dotnet nuget push Castaway/bin/Release/Castaway.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
